import type { Casino, Bonus, Game } from "./types"

export const CASINOS: Casino[] = [
  {
    id: "1",
    slug: "spinnair",
    name: "Spinnair",
    rank: 1,
    rating: 9.4,
    trust_score: 92,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_pikakasino: true,
    affiliate_url: "https://example.com/spinnair",
    mene_slug: "spinnair",
    welcome_bonus_text: "200 ILMAISKIERROSTA & JOPA 20% CASHBACK JOKA PÄIVÄ",
    welcome_bonus_percent: 0,
    welcome_bonus_max_amount: 0,
    welcome_bonus_min_deposit: 20,
    welcome_bonus_wagering: 0,
    min_deposit: 20,
    withdrawal_time_min_hours: 0,
    withdrawal_time_max_hours: 1,
    license_authority: "MGA",
    license_number: "MGA/B2C/123/2023",
    is_verified: true,
    payment_methods: ["Trustly", "Zimpler", "Brite", "Visa", "Mastercard"],
    game_providers: ["NetEnt", "Play'n GO", "Pragmatic Play", "Evolution"],
    total_games_count: 3200,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi", "en"],
    available_in: ["FI"],
    restricted_in: ["US", "UK"],
    support_languages: ["fi", "en"],
    currencies_accepted: ["EUR"],
    badge: "Toimittajan valinta",
    badge_variant: "gold",
    pros_fi: ["MGA-lisenssi (verovapaat voitot)", "Välitön kotiutus Trustlylla", "20% cashback päivittäin", "Erinomainen mobiilipelaaminen"],
    cons_fi: ["Ei tervetulosbonusta", "Rajoitettu peli valikoima"],
    faq_fi: [
      { q: "Onko Spinnair turvallinen kasino?", a: "Kyllä, Spinnairilla on MGA-lisenssi, joka on yksi arvostetuimmista peliviranomaisten lisensseistä." },
      { q: "Miten nopeasti voin kotiuttaa voitot?", a: "Spinnair tarjoaa välittömät kotiutukset Trustly ja Zimpler maksutavoilla." }
    ],
    meta_title_fi: "Spinnair Kasino Arvostelu 2026 | 200 Ilmaiskierrosta",
    meta_description_fi: "Lue Spinnair kasino arvostelu. 200 ilmaiskierrosta, 20% päivittäinen cashback ja välitön kotiutus. MGA-lisenssi verovapaat voitot.",
  },
  {
    id: "2",
    slug: "lussurio",
    name: "Lussurio Casino",
    rank: 2,
    rating: 9.1,
    trust_score: 88,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_pikakasino: false,
    affiliate_url: "https://example.com/lussurio",
    mene_slug: "lussurio",
    welcome_bonus_text: "300% BONUS 850€ ASTI + 100 ILMAISKIERROSTA",
    welcome_bonus_percent: 300,
    welcome_bonus_max_amount: 850,
    welcome_bonus_min_deposit: 10,
    welcome_bonus_wagering: 35,
    min_deposit: 10,
    withdrawal_time_min_hours: 1,
    withdrawal_time_max_hours: 6,
    license_authority: "Curacao",
    is_verified: true,
    payment_methods: ["Visa", "Mastercard", "Bitcoin", "Ethereum", "Skrill"],
    game_providers: ["Pragmatic Play", "NetEnt", "Microgaming", "Play'n GO"],
    total_games_count: 2800,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi", "en"],
    available_in: ["FI", "DE", "CA"],
    restricted_in: ["US", "UK"],
    support_languages: ["fi", "en"],
    currencies_accepted: ["EUR", "USD", "BTC"],
    badge: "Eksklusiivinen",
    badge_variant: "yellow",
    pros_fi: ["Massiivinen 300% tervetulosbonus", "Nopea kotiutus", "Live kasino"],
    cons_fi: ["Curacao-lisenssi (ei verovapaa)", "35x kierrätysvaatimus"],
  },
  {
    id: "3",
    slug: "iwild",
    name: "IWild Casino",
    rank: 3,
    rating: 9.0,
    trust_score: 86,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_pikakasino: true,
    affiliate_url: "https://example.com/iwild",
    mene_slug: "iwild",
    welcome_bonus_text: "300% BONUS 1000€ ASTI + 100 ILMAISKIERROSTA",
    welcome_bonus_percent: 300,
    welcome_bonus_max_amount: 1000,
    welcome_bonus_min_deposit: 25,
    welcome_bonus_wagering: 40,
    min_deposit: 25,
    withdrawal_time_min_hours: 0,
    withdrawal_time_max_hours: 0,
    license_authority: "Curacao",
    is_verified: true,
    payment_methods: ["Trustly", "Visa", "Mastercard", "PayPal", "Skrill"],
    game_providers: ["Evolution", "Pragmatic Play", "Play'n GO"],
    total_games_count: 4000,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi", "en"],
    available_in: ["FI"],
    restricted_in: ["US"],
    support_languages: ["fi", "en"],
    currencies_accepted: ["EUR"],
    badge: "Koodi: MRG700",
    badge_variant: "yellow",
    pros_fi: ["Yli 4000 peliä", "Välitön kotiutus", "Hyvä live kasino"],
    cons_fi: ["Korkea kierrätysvaatimus", "Rekisteröityminen vaaditaan"],
  },
  {
    id: "4",
    slug: "spinbetter",
    name: "Spinbetter",
    rank: 4,
    rating: 8.9,
    trust_score: 85,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_pikakasino: false,
    affiliate_url: "https://example.com/spinbetter",
    mene_slug: "spinbetter",
    welcome_bonus_text: "200% BONUS 1500€ ASTI + 300 ILMAISKIERROSTA",
    welcome_bonus_percent: 200,
    welcome_bonus_max_amount: 1500,
    welcome_bonus_min_deposit: 10,
    welcome_bonus_wagering: 30,
    min_deposit: 10,
    withdrawal_time_min_hours: 0,
    withdrawal_time_max_hours: 15,
    license_authority: "Curacao",
    is_verified: true,
    payment_methods: ["Trustly", "Zimpler", "Visa", "Mastercard", "Bitcoin"],
    game_providers: ["NetEnt", "Pragmatic Play", "Microgaming", "Evolution", "Play'n GO"],
    total_games_count: 5000,
    live_casino: true,
    sports_betting: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi", "en"],
    available_in: ["FI", "DE"],
    restricted_in: ["US"],
    support_languages: ["fi", "en"],
    currencies_accepted: ["EUR", "USD"],
    badge: "Bonus koodi: GMBL150",
    badge_variant: "yellow",
    pros_fi: ["300 ilmaiskierrosta", "Urheiluvedonlyönti myös", "1-15 min kotiutukset"],
    cons_fi: ["Ei MGA-lisenssiä", "Monimutkainen bonusjärjestelmä"],
  },
  {
    id: "5",
    slug: "spinimax",
    name: "Spinimax",
    rank: 5,
    rating: 8.8,
    trust_score: 83,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_pikakasino: true,
    affiliate_url: "https://example.com/spinimax",
    mene_slug: "spinimax",
    welcome_bonus_text: "150% BONUS 750€ ASTI + 150 ILMAISKIERROSTA",
    welcome_bonus_percent: 150,
    welcome_bonus_max_amount: 750,
    welcome_bonus_min_deposit: 20,
    welcome_bonus_wagering: 25,
    min_deposit: 20,
    withdrawal_time_min_hours: 0,
    withdrawal_time_max_hours: 1,
    license_authority: "Comoro Islands",
    is_verified: true,
    payment_methods: ["Trustly", "Brite", "Visa", "Mastercard"],
    game_providers: ["Pragmatic Play", "Play'n GO", "Relax Gaming"],
    total_games_count: 2500,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi"],
    available_in: ["FI"],
    restricted_in: ["US", "UK"],
    support_languages: ["fi"],
    currencies_accepted: ["EUR"],
    badge: "Uusi Tulokas",
    badge_variant: "gray",
    pros_fi: ["150 ilmaiskierrosta", "Välitön kotiutus", "Alhainen kierrätys 25x"],
    cons_fi: ["Vain suomeksi", "Uusi kasino, ei pitkää historiaa"],
  },
  {
    id: "6",
    slug: "gamblezen",
    name: "Gamblezen",
    rank: 6,
    rating: 8.7,
    trust_score: 82,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_pikakasino: true,
    affiliate_url: "https://example.com/gamblezen",
    mene_slug: "gamblezen",
    welcome_bonus_text: "300% BONUS 1500€ ASTI + 100 ILMAISKIERROSTA",
    welcome_bonus_percent: 300,
    welcome_bonus_max_amount: 1500,
    welcome_bonus_min_deposit: 20,
    welcome_bonus_wagering: 35,
    min_deposit: 20,
    withdrawal_time_min_hours: 0,
    withdrawal_time_max_hours: 1,
    license_authority: "Curacao",
    is_verified: true,
    payment_methods: ["Trustly", "Zimpler", "Brite", "Visa", "Mastercard"],
    game_providers: ["NetEnt", "Play'n GO", "Pragmatic Play", "Evolution"],
    total_games_count: 3500,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi", "en"],
    available_in: ["FI"],
    restricted_in: ["US"],
    support_languages: ["fi", "en"],
    currencies_accepted: ["EUR"],
    badge: "Eksklusiivinen",
    badge_variant: "gold",
    pros_fi: ["300% tervetulosbonus", "High Roller bonukset", "Pikakotiutus"],
    cons_fi: ["Ei MGA-lisenssiä", "Korkea minimitalletus"],
  },
  {
    id: "7",
    slug: "hitnspins",
    name: "HitNSpin",
    rank: 7,
    rating: 8.6,
    trust_score: 81,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_pikakasino: false,
    affiliate_url: "https://example.com/hitnspins",
    mene_slug: "hitnspins",
    welcome_bonus_text: "230% BONUS 1000€ ASTI + 150 ILMAISKIERROSTA",
    welcome_bonus_percent: 230,
    welcome_bonus_max_amount: 1000,
    welcome_bonus_min_deposit: 15,
    welcome_bonus_wagering: 35,
    min_deposit: 15,
    withdrawal_time_min_hours: 1,
    withdrawal_time_max_hours: 6,
    license_authority: "Curacao",
    is_verified: true,
    payment_methods: ["Visa", "Mastercard", "Skrill", "Neteller", "Bitcoin"],
    game_providers: ["Pragmatic Play", "Play'n GO", "NetEnt"],
    total_games_count: 2200,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi", "en"],
    available_in: ["FI", "DE"],
    restricted_in: ["US"],
    support_languages: ["fi", "en"],
    currencies_accepted: ["EUR", "USD"],
    badge: "Suosittu",
    badge_variant: "yellow",
    pros_fi: ["150 ilmaiskierrosta", "Nopea asiakaspalvelu", "Hyvä pelitarjonta"],
    cons_fi: ["Ei pikakasinoa", "Melko korkea kierrätys"],
  },
  {
    id: "8",
    slug: "oha-casino",
    name: "Oha Casino",
    rank: 8,
    rating: 8.5,
    trust_score: 80,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_pikakasino: true,
    affiliate_url: "https://example.com/oha",
    mene_slug: "oha-casino",
    welcome_bonus_text: "200% BONUS 1000€ ASTI",
    welcome_bonus_percent: 200,
    welcome_bonus_max_amount: 1000,
    welcome_bonus_min_deposit: 20,
    welcome_bonus_wagering: 30,
    min_deposit: 20,
    withdrawal_time_min_hours: 0,
    withdrawal_time_max_hours: 1,
    license_authority: "Comoro Islands",
    is_verified: true,
    payment_methods: ["Trustly", "Brite", "Visa", "Mastercard"],
    game_providers: ["Pragmatic Play", "NetEnt", "Play'n GO"],
    total_games_count: 2000,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi"],
    available_in: ["FI"],
    restricted_in: ["US"],
    support_languages: ["fi"],
    currencies_accepted: ["EUR"],
    badge: "Uusi 2026",
    badge_variant: "gray",
    pros_fi: ["Reilu 30x kierrätys", "Välitön kotiutus", "Uusi moderni kasino"],
    cons_fi: ["Vasta perustettu", "Suppeampi pelitarjonta"],
  },
  {
    id: "9",
    slug: "ybets",
    name: "Ybets Casino",
    rank: 9,
    rating: 8.4,
    trust_score: 79,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_pikakasino: false,
    affiliate_url: "https://example.com/ybets",
    mene_slug: "ybets",
    welcome_bonus_text: "200% BONUS 2000€ ASTI + 100 ILMAISKIERROSTA",
    welcome_bonus_percent: 200,
    welcome_bonus_max_amount: 2000,
    welcome_bonus_min_deposit: 10,
    welcome_bonus_wagering: 40,
    min_deposit: 10,
    withdrawal_time_min_hours: 0,
    withdrawal_time_max_hours: 2,
    license_authority: "Philippines",
    is_verified: true,
    payment_methods: ["Bitcoin", "Ethereum", "Visa", "Mastercard", "Skrill"],
    game_providers: ["Pragmatic Play", "Evolution", "NetEnt"],
    total_games_count: 3000,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["en"],
    available_in: ["FI", "DE", "CA"],
    restricted_in: ["US"],
    support_languages: ["en"],
    currencies_accepted: ["EUR", "USD", "BTC", "ETH"],
    badge: "Krypto-ystävällinen",
    badge_variant: "yellow",
    pros_fi: ["Kryptovaluutat hyväksytään", "Erittäin nopea kotiutus", "2000€ tervetulosbonus"],
    cons_fi: ["Korkea kierrätys 40x", "Asiakastuki vain englanniksi"],
  },
  {
    id: "10",
    slug: "stakes-casino",
    name: "Stakes Casino",
    rank: 10,
    rating: 8.3,
    trust_score: 78,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_pikakasino: false,
    affiliate_url: "https://example.com/stakes",
    mene_slug: "stakes-casino",
    welcome_bonus_text: "200% BONUS 500€ ASTI + 50 ILMAISKIERROSTA",
    welcome_bonus_percent: 200,
    welcome_bonus_max_amount: 500,
    welcome_bonus_min_deposit: 10,
    welcome_bonus_wagering: 0,
    min_deposit: 10,
    withdrawal_time_min_hours: 1,
    withdrawal_time_max_hours: 24,
    license_authority: "Curacao",
    is_verified: true,
    payment_methods: ["Trustly", "Visa", "Mastercard", "Bitcoin"],
    game_providers: ["Pragmatic Play", "Play'n GO", "NetEnt"],
    total_games_count: 2600,
    live_casino: true,
    mobile_optimized: true,
    live_chat_support: true,
    languages_supported: ["fi", "en"],
    available_in: ["FI"],
    restricted_in: ["US"],
    support_languages: ["fi", "en"],
    currencies_accepted: ["EUR"],
    badge: "Eksklusiivinen",
    badge_variant: "gold",
    pros_fi: ["Kierrätysvapaa bonus", "Eksklusiivinen tarjous", "Luotettava kasino"],
    cons_fi: ["Pienehkö tervetulosbonus", "Ei MGA-lisenssiä"],
  },
]

export const BONUS_TYPES = [
  { id: "welcome", label_fi: "Tervetulisbonukset", label_en: "Welcome Bonuses", label_uk: "Welcome Bonuses" },
  { id: "no_deposit", label_fi: "Ei Talletusta", label_en: "No Deposit", label_uk: "No Deposit" },
  { id: "free_spins", label_fi: "Ilmaispyöräytykset", label_en: "Free Spins", label_uk: "Free Spins" },
  { id: "cashback", label_fi: "Cashback", label_en: "Cashback", label_uk: "Cashback" },
]

export const FILTER_OPTIONS = {
  licenses: ["MGA", "UKGC", "Curacao", "Comoro Islands", "Costa Rica", "Philippines"],
  payment_methods: ["Trustly", "Zimpler", "Brite", "Visa", "Mastercard", "PayPal", "Skrill", "Bitcoin"],
  bonus_types: ["Tervetulosbonus", "Ilmaispyöräytykset", "Cashback", "Ei kierrätystä"],
  providers: ["NetEnt", "Microgaming", "Play'n GO", "Pragmatic Play", "Evolution"],
}

export const HERO_SLIDES = [
  {
    id: 1,
    casinoName: "SPIN PLATINUM",
    bonus: "100% BONUS 500€ ASTI + 100FS",
    subtext: "ZIMPLER TALLETUKSET JA NOSTOT",
    bgColor: "bg-[#E0FCF9]",
    textColor: "text-[#1B1B1C]",
    bonusColor: "text-[#26039d]",
    btnClass: "bg-[#26039d] text-white",
    slug: "spinplatinum",
  },
  {
    id: 2,
    casinoName: "BLINGI",
    bonus: "TALLETA JA SAA 250 ILMAISKIERROSTA",
    subtext: "LISÄKSI SAAT 20% CASHBACK JOKA PÄIVÄ",
    bgColor: "bg-[#232323]",
    textColor: "text-white",
    bonusColor: "text-white",
    btnClass: "bg-[#97FF00] text-black",
    accentColor: "text-[#97FF00]",
    slug: "blingi",
  },
  {
    id: 3,
    casinoName: "CASH LOUNGE",
    bonus: "150% NOSTICKY 1000€ ASTI + 150FS",
    subtext: "VEDONLYÖNTI: 100% AINA 300€ ASTI",
    bgColor: "bg-[#0D2E24]",
    textColor: "text-[#F3C46C]",
    bonusColor: "text-white",
    btnClass: "bg-[#F3C46C] text-[#0D2E24]",
    slug: "cashlounge",
  },
]

// ─── BONUSES ────────────────────────────────────────────────────────────────
export const BONUSES: Bonus[] = [
  { id: "b1", casino_id: "2", casino_name: "Lussurio Casino", casino_slug: "lussurio", title: "300% Tervetulosbonus 850€ asti + 100 FS", description: "Talleta vähintään 10€ ja saat 300% bonuksen 850€ asti sekä 100 ilmaiskierrosta.", bonus_type: "welcome", amount: "300% / 850€", wagering: 35, min_deposit: 10, is_featured: true, lang: "fi" },
  { id: "b2", casino_id: "4", casino_name: "Bob Casino", casino_slug: "bob-casino", title: "100% Bonus 200€ + 200 Ilmaiskierrosta", description: "Uusille pelaajille 100% tervetulosbonus 200€ asti ja 200 ilmaiskierrosta.", bonus_type: "welcome", amount: "100% / 200€", wagering: 40, min_deposit: 20, is_featured: true, lang: "fi" },
  { id: "b3", casino_id: "5", casino_name: "Cbet Casino", casino_slug: "cbet-casino", title: "200% Bonus 500€ asti", description: "200% tervetulosbonus 500€ asti kaikille uusille pelaajille.", bonus_type: "welcome", amount: "200% / 500€", wagering: 30, min_deposit: 20, is_featured: false, lang: "fi" },
  { id: "b4", casino_id: "1", casino_name: "Spinnair", casino_slug: "spinnair", title: "20 Ilmaiskierrosta Ilman Talletusta", description: "Rekisteröidy ja saa 20 ilmaiskierrosta heti ilman talletusta.", bonus_type: "no_deposit", amount: "20 FS", wagering: 0, min_deposit: 0, is_featured: true, lang: "fi" },
  { id: "b5", casino_id: "3", casino_name: "IWild Casino", casino_slug: "iwild", title: "50 Ilmaiskierrosta No Deposit", description: "Avaa tili ja saat 50 ilmaiskierrosta ilman talletusvaatimusta.", bonus_type: "no_deposit", amount: "50 FS", wagering: 0, min_deposit: 0, is_featured: false, lang: "fi" },
  { id: "b6", casino_id: "6", casino_name: "N1 Casino", casino_slug: "n1-casino", title: "200 Ilmaiskierrosta Book of Dead", description: "100% bonus 400€ asti + 200 ilmaiskierrosta Book of Dead -peliin.", bonus_type: "free_spins", amount: "200 FS", wagering: 40, min_deposit: 20, is_featured: true, lang: "fi" },
  { id: "b7", casino_id: "7", casino_name: "Nomini Casino", casino_slug: "nomini-casino", title: "150 Ilmaiskierrosta + 100% Bonus", description: "Ensitalletusbonuksesi sisältää 100% bonuksen ja 150 ilmaiskierrosta.", bonus_type: "free_spins", amount: "150 FS", wagering: 35, min_deposit: 15, is_featured: false, lang: "fi" },
  { id: "b8", casino_id: "1", casino_name: "Spinnair", casino_slug: "spinnair", title: "20% Päivittäinen Cashback", description: "Saat 20% cashbackin jokaisesta häviöstä päivittäin — ilman kierrätysvaatimusta.", bonus_type: "cashback", amount: "20% päivittäin", wagering: 0, min_deposit: 20, is_featured: true, lang: "fi" },
  { id: "b9", casino_id: "8", casino_name: "Jackpot Village", casino_slug: "jackpot-village", title: "15% Viikoittainen Cashback", description: "Kaikki pelaajat saavat 15% cashbackin viikoittaisista häviöistään.", bonus_type: "cashback", amount: "15% viikottain", wagering: 5, min_deposit: 20, is_featured: false, lang: "fi" },
]

// ─── GAMES ──────────────────────────────────────────────────────────────────
export const GAMES: Game[] = [
  { id: "g1", slug: "gates-of-olympus", name: "Gates of Olympus", provider: "Pragmatic Play", rtp: 96.5, volatility: "high", type: "slot" },
  { id: "g2", slug: "book-of-dead", name: "Book of Dead", provider: "Play'n GO", rtp: 96.21, volatility: "high", type: "slot" },
  { id: "g3", slug: "starburst", name: "Starburst", provider: "NetEnt", rtp: 96.09, volatility: "low", type: "slot" },
  { id: "g4", slug: "sweet-bonanza", name: "Sweet Bonanza", provider: "Pragmatic Play", rtp: 96.48, volatility: "high", type: "slot" },
  { id: "g5", slug: "big-bass-bonanza", name: "Big Bass Bonanza", provider: "Pragmatic Play", rtp: 96.71, volatility: "high", type: "slot" },
  { id: "g6", slug: "reactoonz", name: "Reactoonz", provider: "Play'n GO", rtp: 96.51, volatility: "high", type: "slot" },
  { id: "g7", slug: "gonzos-quest", name: "Gonzo's Quest", provider: "NetEnt", rtp: 95.97, volatility: "medium", type: "slot" },
  { id: "g8", slug: "mega-moolah", name: "Mega Moolah", provider: "Microgaming", rtp: 88.12, volatility: "medium", type: "jackpot" },
  { id: "g9", slug: "lightning-roulette", name: "Lightning Roulette", provider: "Evolution", rtp: 97.30, volatility: "medium", type: "live" },
  { id: "g10", slug: "crazy-time", name: "Crazy Time", provider: "Evolution", rtp: 96.08, volatility: "high", type: "live" },
  { id: "g11", slug: "immersive-roulette", name: "Immersive Roulette", provider: "Evolution", rtp: 97.30, volatility: "low", type: "live" },
  { id: "g12", slug: "blackjack-vip", name: "Blackjack VIP", provider: "Evolution", rtp: 99.29, volatility: "low", type: "table" },
  { id: "g13", slug: "wanted-dead-or-a-wild", name: "Wanted Dead or a Wild", provider: "Hacksaw Gaming", rtp: 96.38, volatility: "high", type: "slot" },
  { id: "g14", slug: "sugar-rush", name: "Sugar Rush 1000", provider: "Pragmatic Play", rtp: 96.53, volatility: "high", type: "slot" },
  { id: "g15", slug: "dog-house-megaways", name: "Dog House Megaways", provider: "Pragmatic Play", rtp: 96.55, volatility: "high", type: "slot" },
  { id: "g16", slug: "rise-of-merlin", name: "Rise of Merlin", provider: "Play'n GO", rtp: 96.51, volatility: "high", type: "slot" },
]

// ─── RAFFLES ────────────────────────────────────────────────────────────────
export const RAFFLES = [
  {
    id: "r1",
    title: "Viikkoraffle #47 — iPhone 15 Pro",
    prize: "iPhone 15 Pro (1 299€)",
    casino_name: "Spinnair",
    casino_slug: "spinnair",
    ends_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    how_to: ["Rekisteröidy Spinnairille", "Tee vähintään 20€ talletus", "Pelaa 100€ edestä kolikkopeleissä", "Olet mukana arvonnassa!"],
    past_winners: [
      { name: "Mikko T.", prize: "500€ käteinen", casino: "Spinnair", date: "2026-01-10" },
      { name: "Laura K.", prize: "PS5 konsoli", casino: "Lussurio", date: "2026-01-03" },
      { name: "Janne M.", prize: "AirPods Pro", casino: "IWild", date: "2025-12-27" },
      { name: "Sanna V.", prize: "200€ käteinen", casino: "Bob Casino", date: "2025-12-20" },
    ],
    upcoming: [
      { id: "r2", title: "Raffle #48 — 500€ Käteinen", prize: "500€", starts_at: "2026-01-25", casino: "Lussurio Casino" },
      { id: "r3", title: "Raffle #49 — PS5 + 3 peliä", prize: "PS5 Bundle", starts_at: "2026-02-01", casino: "IWild Casino" },
    ],
  },
]

// ─── BONUS HUNT ─────────────────────────────────────────────────────────────
export const BONUS_HUNTS = [
  {
    id: "bh1",
    title: "Bonushunt #23 — Live Session",
    date: "2026-01-17",
    is_active: true,
    total_invested: 1240,
    total_won: 0,
    currency: "€",
    slots: [
      { game: "Gates of Olympus", provider: "Pragmatic Play", balance: 200, bet: 2.0, bonus_value: 14, multiplier: null },
      { game: "Sweet Bonanza", provider: "Pragmatic Play", balance: 180, bet: 1.5, bonus_value: 12, multiplier: null },
      { game: "Book of Dead", provider: "Play'n GO", balance: 160, bet: 2.0, bonus_value: 10, multiplier: null },
      { game: "Dog House Megaways", provider: "Pragmatic Play", balance: 220, bet: 3.0, bonus_value: 14, multiplier: null },
      { game: "Wanted Dead or a Wild", provider: "Hacksaw Gaming", balance: 200, bet: 2.0, bonus_value: 12, multiplier: null },
      { game: "Big Bass Bonanza", provider: "Pragmatic Play", balance: 140, bet: 1.0, bonus_value: 8, multiplier: null },
      { game: "Reactoonz", provider: "Play'n GO", balance: 140, bet: 2.0, bonus_value: 8, multiplier: null },
    ],
  },
  {
    id: "bh2",
    title: "Bonushunt #22 — Lopputulos",
    date: "2026-01-10",
    is_active: false,
    total_invested: 1800,
    total_won: 4320,
    currency: "€",
    slots: [
      { game: "Gates of Olympus", provider: "Pragmatic Play", balance: 300, bet: 3.0, bonus_value: 14, multiplier: 342 },
      { game: "Sweet Bonanza", provider: "Pragmatic Play", balance: 250, bet: 2.0, bonus_value: 12, multiplier: 87 },
      { game: "Book of Dead", provider: "Play'n GO", balance: 200, bet: 2.0, bonus_value: 10, multiplier: 45 },
      { game: "Wanted Dead or a Wild", provider: "Hacksaw Gaming", balance: 300, bet: 3.0, bonus_value: 12, multiplier: 210 },
      { game: "Big Bass Bonanza", provider: "Pragmatic Play", balance: 150, bet: 1.0, bonus_value: 8, multiplier: 23 },
      { game: "Reactoonz", provider: "Play'n GO", balance: 200, bet: 2.0, bonus_value: 8, multiplier: 67 },
      { game: "Sugar Rush 1000", provider: "Pragmatic Play", balance: 400, bet: 4.0, bonus_value: 16, multiplier: 1240 },
    ],
  },
]

export const TRANSLATIONS = {
  fi: {
    nav: {
      casinos: "Kasinot",
      bonuses: "Bonukset",
      games: "Pelit",
      raffles: "Rafflet",
      bonushunt: "Bonushunt",
    },
    hero: {
      badge: "Päivitetty Tammikuu 2026",
      title: "Vuoden 2026",
      titleHighlight: "Parhaat Nettikasinot",
      titleSuffix: "Suomessa",
      subtitle: "Eksklusiiviset bonukset, verovapaat voitot ja nopeimmat kotiutukset. Tiimimme on testannut ja arvostellut satoja kasinoita puolestasi.",
      trust1: "MGA-Lisenssi",
      trust2: "Pikakotiutukset",
      trust3: "Suomalainen tuki",
      cta: "Pelaa Nyt",
    },
    filters: {
      quickCasinos: "Pikakasinot",
      newCasinos: "Uudet Kasinot",
      nonSticky: "Non-Sticky Bonukset",
      taxFree: "Verovapaat",
      freeSpins: "Ilmaispyöräytykset",
    },
    listing: {
      title: "Parhaaksi Arvioidut Kasinot",
      subtitle: "Valikoitujen asiantuntijoiden parhaat poiminnot tälle viikolle.",
      sortBy: "Järjestä: Suosituimmat",
      playNow: "Pelaa Nyt",
      readReview: "Lue Arvostelu",
      showMore: "Näytä loput nettikasinot",
      minDeposit: "Minimitalletus",
      withdrawalSpeed: "Kotiutusnopeus",
      license: "Lisenssi",
      bonusType: "Bonus tyyppi",
      instant: "Välitön",
    },
    footer: {
      description: "Suomen kattavin opas nettikasinoihin ja bonuksiin. Autamme sinua löytämään parhaat pelikokemukset turvallisesti.",
      quicklinks: "Pikalinkit",
      about: "Tietoa meistä",
      responsibility: "Vastuullisuus",
      copyright: "© 2026 SlotsBand. Kaikki oikeudet pidätetään.",
      bestCasinos: "Parhaat nettikasinot",
      quickCasinos: "Pikakasinot",
      contact: "Ota yhteyttä",
      responsibleGambling: "Vastuullinen pelaaminen",
      disclaimer: "Muistathan, että rahapelaaminen voi aiheuttaa riippuvuutta. Pelaa vastuullisesti. 18+",
    },
    search: "Etsi kasinoita...",
  },
  en: {
    nav: {
      casinos: "Casinos",
      bonuses: "Bonuses",
      games: "Games",
      raffles: "Raffles",
      bonushunt: "Bonus Hunt",
    },
    hero: {
      badge: "Updated January 2026",
      title: "Best Online Casinos",
      titleHighlight: "for 2026",
      titleSuffix: "",
      subtitle: "Exclusive bonuses, fast withdrawals, and expert reviews. Our team has tested and reviewed hundreds of casinos for you.",
      trust1: "MGA Licensed",
      trust2: "Fast Withdrawals",
      trust3: "Expert Reviews",
      cta: "Play Now",
    },
    filters: {
      quickCasinos: "Quick Casinos",
      newCasinos: "New Casinos",
      nonSticky: "Non-Sticky Bonuses",
      taxFree: "Tax-Free",
      freeSpins: "Free Spins",
    },
    listing: {
      title: "Top Rated Casinos",
      subtitle: "Our editors top picks for this week.",
      sortBy: "Sort by: Most Popular",
      playNow: "Play Now",
      readReview: "Read Review",
      showMore: "Show more casinos",
      minDeposit: "Min Deposit",
      withdrawalSpeed: "Withdrawal Speed",
      license: "License",
      bonusType: "Bonus Type",
      instant: "Instant",
    },
    footer: {
      description: "Finland's most comprehensive guide to online casinos and bonuses. We help you find the best gaming experiences safely.",
      quicklinks: "Quick Links",
      about: "About Us",
      responsibility: "Responsibility",
      copyright: "© 2026 SlotsBand. All rights reserved.",
      bestCasinos: "Best online casinos",
      quickCasinos: "Quick casinos",
      contact: "Contact us",
      responsibleGambling: "Responsible gambling",
      disclaimer: "Gambling can be addictive. Play responsibly. 18+",
    },
    search: "Search casinos...",
  },
  uk: {
    nav: {
      casinos: "Casinos",
      bonuses: "Bonuses",
      games: "Games",
      raffles: "Raffles",
      bonushunt: "Bonus Hunt",
    },
    hero: {
      badge: "Updated January 2026",
      title: "Best Online Casinos",
      titleHighlight: "UK 2026",
      titleSuffix: "",
      subtitle: "Exclusive bonuses, UKGC licensed casinos and fast withdrawals. Expert reviews for UK players.",
      trust1: "UKGC Licensed",
      trust2: "Fast Payouts",
      trust3: "UK Support",
      cta: "Play Now",
    },
    filters: {
      quickCasinos: "New Casinos",
      newCasinos: "Top Casinos",
      nonSticky: "No Wager Bonuses",
      taxFree: "Top Rated",
      freeSpins: "Free Spins",
    },
    listing: {
      title: "Top Rated UK Casinos",
      subtitle: "Expert picks for UK players in 2026.",
      sortBy: "Sort by: Most Popular",
      playNow: "Play Now",
      readReview: "Read Review",
      showMore: "Show more casinos",
      minDeposit: "Min Deposit",
      withdrawalSpeed: "Withdrawal Speed",
      license: "License",
      bonusType: "Bonus Type",
      instant: "Instant",
    },
    footer: {
      description: "The UK's trusted guide to online casinos and bonuses. Safe, expert-reviewed recommendations.",
      quicklinks: "Quick Links",
      about: "About Us",
      responsibility: "Responsibility",
      copyright: "© 2026 SlotsBand. All rights reserved.",
      bestCasinos: "Best online casinos",
      quickCasinos: "New casinos",
      contact: "Contact us",
      responsibleGambling: "Responsible gambling",
      disclaimer: "Gambling can be addictive. 18+ only. Please gamble responsibly. BeGambleAware.org",
    },
    search: "Search casinos...",
  },
}
